### ISSUE TITLE
The original repository looks abandoned

### ISSUE THREAD

**Issue by NoahAndrews** [DeviceFarmer/adbkit#14]
I got pretty scared when I saw that https://github.com/openstf/adbkit had been archived. Thankfully, I found the note at https://github.com/openstf/stf, saying that all of the repositories had been moved here. That message should be posted to all of the old repositories, if at all possible.

**Comment by koral--** [comment]
Good catch. Thanks.
I believe I've added such notice to each repo but this one was an oversight.
