### ISSUE TITLE
Question about release note.

### ISSUE THREAD

**Issue by slugger941** [DeviceFarmer/adbkit#231]
Is there no release note?
I want to check which parts have been improved or which have been changed for each version.

**Comment by koral--** [comment]
https://github.com/DeviceFarmer/adbkit/releases/tag/v3.2.1

**Comment by koral--** [comment]
After moving from OpenSTF to DeviceFarmer there was only one more release: https://github.com/DeviceFarmer/adbkit/releases/tag/v3.2.0
