### ISSUE TITLE
3 vulnerabilities while running 'npm audit'

### ISSUE THREAD

**Issue by MilkFlavor** [DeviceFarmer/adbkit#248]
I got some moderate to low warnings/errors while installing the library:
1. **Low** Prototype Pollution in node-forge debug API. 
2. **Low**  URL parsing in node-forge could lead to undesired behavior.
3. **Moderate** Open Redirect in node-forge 

While running 'npm audit' https://pastebin.com/Zjshpu9A

**Comment by mdesantis** [comment]
Same here. It seems that node-forge dependency bump is blocked by this PR: https://github.com/DeviceFarmer/adbkit/pull/227 whose build is broken

**Comment by julienw** [comment]
See also https://github.com/DeviceFarmer/adbkit/pull/230

**Comment by MilkFlavor** [comment]
So should we just @pimterry's solution to fix these dependency problems?

"In the meantime, for anybody else struggling with this, in NPM v8.3+ you can now override adbkit's dependency version in your package.json using:

```json
"overrides": {
    "@devicefarmer/adbkit": {
      "node-forge": "^1.0.0"
    }
}
``` "

_Originally posted in https://github.com/DeviceFarmer/adbkit/issues/230#issuecomment-1030094967_

**Comment by UrielCh** [comment]
Maybe you can try [@u4/adbkit](https://www.npmjs.com/package/@u4/adbkit)
in this version `npm audit` passes with no warning.
