### ISSUE TITLE
getPackages flags/filter

### ISSUE THREAD

**Issue by ov3rk1ll** [DeviceFarmer/adbkit#55]
The `pm list packages` command has some flags that allow to filter the list of returned packages:
```
-d: filter to only show disabled packages
-e: filter to only show enabled packages
-s: filter to only show system packages
-3: filter to only show third party packages
```

It would be nice if this flag can be supplied when using the `client.getPackages` function.  
I think a raw, optional string would be the easiest solution here.

If you are interested in such a change, I can provide a MR for this.

**Comment by koral--** [comment]
Sure feel free to submit a PR.

**Comment by koral--** [comment]
Done in #56
