### ISSUE TITLE
typescript type not found

### ISSUE THREAD

**Issue by qhkm** [DeviceFarmer/adbkit#85]
I'm not sure if this is the right place to ask this question but is there any typescript typedef anywhere as  i could'nt find it anywhere (definitelyTyped). If there's none, will try my best to take some time to contribute. Thank you!

**Comment by NoahAndrews** [comment]
The code has actually been rewritten in TS. Unfortunately, a new version hasn't come out since then.

**Comment by qhkm** [comment]
Appreciate your response. Got that.

**Comment by drauggres** [comment]
To have a proper type declarations was one of the goals when I was rewriting code in TS. But compatible version was never released.
In my project I did this:

1. Build adbkit from [this commit](https://github.com/DeviceFarmer/adbkit/commit/8d011fa862d1465415864a41b6e347f3fffa8442)
- `git clone https://github.com/DeviceFarmer/adbkit.git`
- `cd adbkit`
- `git checkout 8d011fa862d1465415864a41b6e347f3fffa8442`
- `npm i` (this command will not only install dependencies, but also build the lib and run tests)
2. Copy types to my project
- `mkdir -p /path/to/my/project/typings/@devicefarmer/adbkit`
- `find . ! \( -path './node_modules' -prune \) -name \*.d.ts  -exec cp --parents \{\} /path/to/my/project/typings/@devicefarmer/adbkit \;` (single line. run from adbkit root. explanation: copy all relevant `*.d.ts` to my project saving structure)
3. Configure tsconfig.json
- add `"typeRoots": ["./typings"]` ([doc](https://www.typescriptlang.org/tsconfig#typeRoots))

This way I can use the last released version (`@devicefarmer/adbkit@2.11.3`) with TypeScript.

P.S. you will also need to add `@types/bluebird` and `@types/node-forge` to `devDependencies` in your project for it to work properly.

**Comment by koral--** [comment]
Sorry for the delay, I'll release new versions of all the DeviceFarmer components ASAP.
Will keep this issue open until it happens.

**Comment by koral--** [comment]
@drauggres it seems that we have an issue with TS:
> tsc  -p .00:13
src/adb/DeviceClient.ts:383:51 - error TS2345: Argument of type '{ fixLineFeeds: false; }' is not assignable to parameter of type 'ReaderOptions'.00:13
  Type '{ fixLineFeeds: false; }' is missing the following properties from type 'ReaderOptions': format, priority00:13
383       .then((stream) => Logcat.readStream(stream, { fixLineFeeds: false }));

https://devicefarmer.semaphoreci.com/jobs/1f23bc72-30fc-4c88-b47a-931b525a2539

Do you have maybe some idea how to fix it in the best way?

**Comment by drauggres** [comment]
IDK, my code is gone after #79 was merged. I wasn't able to review the changes and have no idea what is happening in the `master`.

@UrielCh

**Comment by koral--** [comment]
OK, I've reverted those changes from #79 for now.

**Comment by koral--** [comment]
@drauggres I've checked that deeper and the last commit which builds (passes `npm install`) w/o error is 3bd94baf932d18815e6e10c383b186cafb7effaa from https://github.com/DeviceFarmer/adbkit/pull/31 
The next one 948713e871935d737222e105a8934e0981414005 from PR https://github.com/DeviceFarmer/adbkit/pull/38 does not build.

It looks like integration process does not work here properly, need to investigate that.
But any other idea how to clean up the status for now, except for moving back to last working commit?

**Comment by drauggres** [comment]
> @drauggres I've checked that deeper and the last commit which builds (passes `npm install`) w/o error is [3bd94ba](https://github.com/DeviceFarmer/adbkit/commit/3bd94baf932d18815e6e10c383b186cafb7effaa) from #31
> The next one [948713e](https://github.com/DeviceFarmer/adbkit/commit/948713e871935d737222e105a8934e0981414005) from PR #38 does not build.

You probably forgot to clean `node_modules` between builds. `npm i` works fine with empty `node_modules` on both mentioned above commits.

**Comment by koral--** [comment]
Yeah, that's the reason 🤦

**Comment by drauggres** [comment]
Now (with `@devicefarmer/adbkit-logcat@2.1.1) you should be able to release v3.
But I'm going to stick with v2 for some time, until something interesting appears in the new version.

**Comment by koral--** [comment]
Thanks @drauggres for the help with resolving this.
And sorry for acting in rush as you spotted. 
Basically I have a limited time and wanted to release as much as possible.

Closing this issue as version 3.2.0 was released.
