### ISSUE TITLE
Roll-back hard fork.

### ISSUE THREAD

**Issue by UrielCh** [DeviceFarmer/adbkit#99]
Hi, I have to switch to some new projects, and now I'm back to android.

It looks like you finally merge my changes.

I was about to add some helpers to access ProcessList and to kill a process.

What part of my PR did you merge?

Did you update the doc to match method parameters?

What your point of view about removing the doc from the README.md, and generating it from the source, to avoid maintaining 2 copies of the doc.

**Comment by UrielCh** [comment]
Why did you skip version numbers 3.0.0 and 3.1.0?

**Comment by koral--** [comment]
Sorry, I've missed your messages and just saw only the notification about issue closure.

> Why did you skip version numbers 3.0.0 and 3.1.0?

AFAIR they turned out unstable.

> What your point of view about removing the doc from the README.md, and generating it from the source, to avoid maintaining 2 copies of the doc.

I agree.

> Did you update the doc to match method parameters?

no

> What part of my PR did you merge?

AFAIR most of your PR was reverted due to fatal errors in runtime at start.

**Comment by drauggres** [comment]
> AFAIR most of your PR was reverted due to fatal errors in runtime at start.

It's all still there.

**Comment by koral--** [comment]
Thanks for the correction.
